let D,w=1;const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],DAY=['星期一','星期二','星期三','星期四','星期五'];
const pad=n=>String(n).padStart(2,'0'),date=s=>new Date(s+'T00:00:00'),iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,add=(d,n)=>{let x=new Date(d);x.setDate(x.getDate()+n);return x},md=d=>`${d.getMonth()+1}/${d.getDate()}`,ymd=d=>`${d.getFullYear()}/${pad(d.getMonth()+1)}/${pad(d.getDate())}`;
function current(){let n=Math.floor((date(iso(new Date()))-date(D.term_start))/6048e5)+1;return Math.max(1,Math.min(D.week_count,n))}function dates(n){let s=add(date(D.term_start),(n-1)*7);return DAY.map((_,i)=>add(s,i))}function internship(s){return s>=D.internship.start&&s<=D.internship.end}function events(s){return D.special_events.filter(e=>e.date===s)}
function label(b){let a=b.start_period,z=b.end_period,p=a===z?`第${a}節`:`第${a}–${z}節`,t=`${D.periods[a].start}–${D.periods[z].end}`;return[p,t]}
function blocks(d,fixed=false){let s=iso(d),wd=d.getDay(),ev=fixed?[]:events(s),stop=ev.some(e=>e.all_day&&['holiday','activity'].includes(e.kind));if(!fixed&&internship(s)){let o=ev.filter(e=>!e.all_day);if(!o.length)return[{all_day:true,course:D.internship.title,type:'internship',meta:'10/5–10/25'}]}let a=stop||wd<1||wd>5?[]:D.fixed_schedule.filter(x=>x.weekday===wd).map(x=>({...x}));if(!fixed){let o=ev.filter(e=>!e.all_day).map(e=>({start_period:e.start_period,end_period:e.end_period,course:e.title,teacher:e.teacher||'',room:e.room||'',type:e.kind,meta:e.note||''})),used=new Set;o.forEach(x=>{for(let p=x.start_period;p<=x.end_period;p++)used.add(p)});a=a.filter(x=>{for(let p=x.start_period;p<=x.end_period;p++)if(used.has(p))return false;return true});a.push(...o)}return a.sort((x,y)=>(x.start_period||0)-(y.start_period||0))}
function allday(d){let s=iso(d);if(internship(s))return{title:D.internship.title,kind:'internship',note:'10/5–10/25'};return events(s).find(e=>e.all_day&&['holiday','activity'].includes(e.kind))}
function courseHTML(b){if(b.all_day)return`<div class="course all ${b.type}"><h3>${b.course}</h3><p>${b.meta||''}</p></div>`;let [p,t]=label(b),m=[b.teacher,b.room,b.meta].filter(Boolean).join('｜');return`<article class="course ${b.type||'other'}"><div class="top"><span>${p}</span><span>${t}</span></div><h3>${b.course}</h3>${m?`<p>${m}</p>`:''}</article>`}
function drawDays(target,ds,fixed=false){target.innerHTML=ds.map((d,i)=>{let a=fixed?null:allday(d),b=blocks(d,fixed),html=a?`<div class="course all ${a.kind}"><h3>${a.title}</h3><p>${a.note||''}</p></div>`:'';html+=b.map(courseHTML).join('');if(!html)html='<div class="empty">目前無固定課程</div>';return`<section class="day"><header class="day-head"><strong>${DAY[i]}</strong><small>${ymd(d)}</small></header><div class="day-body">${html}</div></section>`}).join('')}
function weekEvents(n){let ds=dates(n),a=iso(ds[0]),b=iso(ds[4]),x=D.special_events.filter(e=>e.date>=a&&e.date<=b);if(ds.some(d=>internship(iso(d))))x.push({kind:'internship',title:D.internship.title});return x}
function drawWeek(){let ds=dates(w);$('#weekTitle').textContent=`第 ${w} 週｜${md(ds[0])}－${md(ds[4])}`;$('#weekSub').textContent=`${D.semester}・${D.class_name}`;$('#weekSelect').value=w;$('#prev').disabled=w===1;$('#next').disabled=w===D.week_count;let seen=new Set;$('#weekTags').innerHTML=weekEvents(w).filter(e=>{let k=e.kind+e.title;if(seen.has(k))return false;seen.add(k);return true}).map(e=>`<span class="tag ${e.kind}">${e.date?md(date(e.date))+' ':''}${e.title}</span>`).join('');drawDays($('#weekDays'),ds)}
function drawFixed(){drawDays($('#fixedDays'),dates(1),true)}function drawWeeks(){let now=current();$('#weeks').innerHTML=Array.from({length:D.week_count},(_,i)=>{let n=i+1,ds=dates(n),seen=new Set,t=weekEvents(n).filter(e=>{let k=e.kind+e.title;if(seen.has(k))return false;seen.add(k);return true});return`<article class="week-card${n===now?' now':''}" data-week="${n}"><h3>第 ${n} 週${n===now?'・目前週次':''}</h3><div class="dates">${ymd(ds[0])}－${ymd(ds[4])}</div><div class="mini">${t.length?t.map(e=>`<span class="${e.kind}">${e.title}</span>`).join(''):'<span>一般上課週</span>'}</div></article>`}).join('');$$('.week-card').forEach(x=>x.onclick=()=>{w=+x.dataset.week;openTab('week');drawWeek();scrollTo({top:180,behavior:'smooth'})})}
function text(){let ds=dates(w),a=[`5N403｜第${w}週（${md(ds[0])}－${md(ds[4])}）`];ds.forEach((d,i)=>{let x=[],ad=allday(d);if(ad)x.push(ad.title);blocks(d).forEach(b=>x.push(b.all_day?b.course:`${label(b)[0]} ${b.course}`));a.push(`${DAY[i]}：${x.length?x.join('、'):'無固定課程'}`)});a.push(D.notice);return a.join('\n')}
function toast(s){let x=$('#toast');x.textContent=s;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1700)}async function copy(s){try{await navigator.clipboard.writeText(s);toast('已複製')}catch{toast('請長按複製')}}function openTab(id){$$('.tab').forEach(x=>x.classList.toggle('on',x.dataset.tab===id));$$('.panel').forEach(x=>x.classList.toggle('on',x.id===id))}
function init(){$('#school').textContent=D.school;$('#short').textContent=D.short_name;$('#slogan').textContent=D.slogan;$('#semester').textContent=D.semester;$('#className').textContent=D.class_name;$('#notice').textContent=D.notice;$('#updated').textContent=`資料更新：${D.updated_at.slice(0,10).replaceAll('-','/')}｜版本 v${D.version}`;$('#weekSelect').innerHTML=Array.from({length:D.week_count},(_,i)=>`<option value="${i+1}">第 ${i+1} 週</option>`).join('');w=current();drawWeek();drawFixed();drawWeeks();$$('.tab').forEach(x=>x.onclick=()=>openTab(x.dataset.tab));$('#prev').onclick=()=>{if(w>1){w--;drawWeek()}};$('#next').onclick=()=>{if(w<D.week_count){w++;drawWeek()}};$('#weekSelect').onchange=e=>{w=+e.target.value;drawWeek()};$('#copy').onclick=()=>copy(text());$('#print').onclick=()=>print();$('#share').onclick=async()=>{if(navigator.share)try{return await navigator.share({title:document.title,text:'5N403｜115-1班級課表',url:location.href})}catch{}copy(location.href)}}
fetch('data.json?v=7',{cache:'no-store'}).then(r=>r.json()).then(x=>{D=x;init()}).catch(()=>document.body.innerHTML='<p style="padding:30px">課表資料載入失敗，請重新整理。</p>');
